project:
  type: website
  resources:
  - assets/
  - CNAME
  - publications.json
  - favicon.ico
  - favicon.png
  - favicon.svg
  - favicon-nps-20260821.ico
  - favicon-nps-20260821.png
  - favicon-nps-20260821.svg
  output-dir: _site

website:
  title: "Nicholas Sweeney"
  description: "Nicholas Sweeney"
  site-url: https://npsweeney.co.uk 
  search: false
  navbar:
    logo-href: /
    left:
      - text: "About"
        href: /
      - text: "Publications"
        href: /publications
      - text: "CV"
        href: /cv
      - text: "Contact"
        href: /contact
  page-footer:
    center: 'Website created by Nicholas Sweeney (Template on <a href="https://github.com/npsweeney/NPS-WEB/tree/main/template" target="_blank" rel="noopener">GitHub</a>)'
  favicon: favicon-nps-20260821.svg

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    header-includes: |
      <link rel="shortcut icon" type="image/x-icon" href="/favicon-nps-20260821.ico">
      <link rel="icon" href="/favicon-nps-20260821.ico" sizes="any">
      <link rel="icon" type="image/png" href="/favicon-nps-20260821.png" sizes="256x256">
